[package]
name = "duit-platform"
version = "0.1.0"
edition = "2018"

[dependencies]
duit = { path = "../duit" }
dume-renderer = { path = "/Users/caelum/dev/dume/renderer" }
glam = "0.17"
pollster = "0.2"
wgpu = "0.10"
winit = { version = "0.25", default-features = false, features = [ "x11" ] }
