variables:
  window: rgb(40, 40, 40)
  background: rgb(70, 70, 70)
  active: rgb(100, 105, 100)
  foreground: rgb(160, 170, 160)
  text_color: rgb(240, 240, 240)
  emphasis: rgb(252, 76, 2)
  
  default_font_family: Cormorant Garamond

styles:
  text:
    default_font_family: $default_font_family
    default_size: 16
    default_color: $text_color
  text & hoverable_text & hovered:
    default_color: $emphasis
  h1:
    default_size: 32
  h2:
    default_size: 24
  h3:
    default_size: 18.72
  h4:
    default_size: 16
  h5:
    default_size: 13.28
  h6:
    default_size: 10.72

  text_input:
    border_radius: 2
    cursor_width: 1
    padding: 5
    font: $default_font_family
    font_size: 16
    font_color: $text_color
    placeholder_font_color: rgb(180, 180, 180)
    background_color: $background
    cursor_color: $foreground
    border_color: $emphasis
    border_width: 0

  text_input & focused:
    background_color: $active
    cursor_color: $foreground
    border_color: $emphasis
    border_width: 1
  
  button:
    padding: 5
    border_radius: 4
    border_width: 0
    border_color: $emphasis
    background_color: $background

  button & hovered:
    border_width: 0
    border_color: $emphasis
    background_color: $active

  button & pressed:
    border_width: 1
    border_color: $emphasis
    background_color: $active

  container:
    border_radius: 1
    border_width: 0.5
    background_color: $window
    border_color: $background

  progress_bar:
    border_radius: 1
    border_width: 1
    border_color: rgb(0, 0, 0)
    background_color: $background
    progress_color: rgb(91, 197, 0)
    projected_progress_color: rgb(62, 154, 44)

  slider:
    line_width: 3
    line_color: $active
    handle_border_radius: 2
    handle_border_width: 1
    handle_border_color: $emphasis
    handle_color: $foreground
    handle_width: 5
    handle_height: 20

  divider:
    line_color: $foreground
    line_width: 1

  table:
    border_width: 1
    border_color: $foreground
    background_color_a: rgb(120, 120, 120)
    background_color_b: rgb(80, 80, 80)
    min_row_height: 20
    min_column_width: 20
    cell_padding: 10
